[theme]
primaryColor="#0F766E"         # teal-700
backgroundColor="#0B1220"      # near-navy for a pro dark
secondaryBackgroundColor="#111827"  # slate-900
textColor="#E5E7EB"            # gray-200
font="sans serif"
